name: pipecat_smart_turn
description: Cross-platform Flutter plugin for Pipecat Smart Turn v3 semantic endpointing.
version: 0.1.0+1
homepage: https://github.com/rag-wtf/pipecat_smart_turn
repository: https://github.com/rag-wtf/pipecat_smart_turn
publish_to: none


environment:
  sdk: ^3.11.0

flutter:
  plugin:
    platforms:
      android:
        default_package: pipecat_smart_turn_android
      ios:
        default_package: pipecat_smart_turn_ios
      linux:
        default_package: pipecat_smart_turn_linux
      macos:
        default_package: pipecat_smart_turn_macos
      web:
        default_package: pipecat_smart_turn_web
      windows:
        default_package: pipecat_smart_turn_windows

dependencies:
  flutter:
    sdk: flutter
  pipecat_smart_turn_android:
    path: ../pipecat_smart_turn_android
  pipecat_smart_turn_ios:
    path: ../pipecat_smart_turn_ios
  pipecat_smart_turn_linux:
    path: ../pipecat_smart_turn_linux
  pipecat_smart_turn_macos:
    path: ../pipecat_smart_turn_macos
  pipecat_smart_turn_platform_interface:
    path: ../pipecat_smart_turn_platform_interface
  pipecat_smart_turn_web:
    path: ../pipecat_smart_turn_web
  pipecat_smart_turn_windows:
    path: ../pipecat_smart_turn_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
