#!/usr/bin/env python3
"""Generate the mel spectrogram golden file.

This script documents the golden generation process for the
mel spectrogram regression test.

The committed golden was generated by the Dart MelSpectrogram
implementation. To prove upstream parity, extend this script
to compare against transformers.WhisperFeatureExtractor.

To regenerate the Dart golden after intentional preprocessing
changes:
  1. Delete test/goldens/mel_spectrogram_golden.bin
  2. Temporarily restore the auto-generate logic in the test
  3. Run: flutter test test/mel_spectrogram_golden_test.dart
  4. Verify the new golden is correct
  5. Remove the auto-generate logic again

Future improvement (upstream parity):
  pip install transformers torch numpy
  - Generate a 128000-sample fixture with 1s 440 Hz sine
  - Run WhisperFeatureExtractor on it
  - Compare output against mel_spectrogram_golden.bin
"""

import sys


def main():
    """Print regeneration instructions."""
    print(__doc__)
    return 0


if __name__ == "__main__":
    sys.exit(main())
